# Generated by Django 4.0 on 2022-07-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='card',
            field=models.BooleanField(default=False),
        ),
    ]
