# Generated by Django 4.0 on 2022-07-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_subscription_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='card',
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripePaymentId',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripeCustomerId',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripeSubscriptionId',
            field=models.CharField(max_length=900),
        ),
    ]
